management:
  endpoints:
    web.exposure.include: "*"
    health.show-details: "always"

spring.boot.admin.client:
  url: http://admin.servicemesh-with-serverless.svc.cluster.local
  auto-deregistration: true
  register-once: false
  instance.prefer-ip: true

fraudverify.base.url: "http://fraud-verifier.servicemesh-with-serverless.svc.cluster.local"
userservice.base.url: "http://user-service.servicemesh-with-serverless.svc.cluster.local"
cardservice.base.url: "http://card-service.servicemesh-with-serverless.svc.cluster.local"

---
spring.config.activate.on-profile: local
spring.boot.admin.client.url: "http://localhost:8085"

fraudverify.base.url: "http://localhost:8081"
userservice.base.url: "http://localhost:8082"
cardservice.base.url: "http://localhost:8083"
