apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fraud-verifier
  namespace: servicemesh-with-serverless
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/target: "2"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/servicemesh-with-serverless/fraud-verifier
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dspring.profiles.active=openshift
                -Dspring.cloud.config.uri=http://service-config.servicemesh-with-serverless.svc.cluster.local/
            - name: AB_JOLOKIA_OFF
              value: "true"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              scheme: HTTP
